import { Injectable, NotFoundException, InternalServerErrorException } from '@nestjs/common';
import { CoursesRepository } from './courses.repository';
import { CreateCourseDto, UpdateCourseDto } from './dto/course.dto';
import { Course } from './entities/course.entity';
import { CloudinaryService } from '../cloudinary/cloudinary.service';

@Injectable()
export class CoursesService {
  constructor(
    private readonly coursesRepository: CoursesRepository,
    private readonly cloudinaryService: CloudinaryService
  ) {}

  private calculateTotalDuration(lessons: any[]): string {
    // Basic logic to sum durations if they are formatted like "06 hr 03 mins" or similar
    // For now, we will just rely on frontend passing it, or set a dummy if not calculable
    return "Calculated dynamically"; // We'll let the frontend pass totalDuration in the future if needed, or compute properly
  }

  async createWithThumbnail(createCourseDto: CreateCourseDto, file: Express.Multer.File): Promise<Course> {
    try {
      const uploadResult = await this.cloudinaryService.uploadFile(file);
      
      const course: Course = {
        id: '', // Generated by repo
        title: createCourseDto.title,
        description: createCourseDto.description,
        category: createCourseDto.category,
        level: createCourseDto.level,
        price: createCourseDto.price,
        originalPrice: createCourseDto.originalPrice,
        status: createCourseDto.status,
        thumbnailUrl: uploadResult.secure_url,
        thumbnailPublicId: uploadResult.public_id,
        instructorId: createCourseDto.instructorId || 'admin',
        lessons: createCourseDto.lessons || [],
        totalDuration: '', // Computed later
        averageRating: 0,
        ratingCount: 0,
        enrollmentCount: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      
      return this.coursesRepository.create(course);
    } catch (error: any) {
      console.error('SERVICE CREATE ERROR:', error);
      throw new InternalServerErrorException('Failed to upload thumbnail and create course: ' + error.message);
    }
  }

  async create(createCourseDto: CreateCourseDto): Promise<Course> {
    throw new Error('Use createWithThumbnail instead');
  }

  async findAll(): Promise<Course[]> {
    return this.coursesRepository.findAll();
  }

  async findOne(id: string): Promise<Course> {
    const course = await this.coursesRepository.findById(id);
    if (!course) {
      throw new NotFoundException(`Course with ID ${id} not found`);
    }
    return course;
  }

  async updateWithThumbnail(id: string, updateCourseDto: UpdateCourseDto, file: Express.Multer.File): Promise<Course> {
    const existingCourse = await this.findOne(id);
    
    // Upload new
    const uploadResult = await this.cloudinaryService.uploadFile(file);
    
    // Delete old
    if (existingCourse.thumbnailPublicId) {
      await this.cloudinaryService.deleteFile(existingCourse.thumbnailPublicId).catch(console.error);
    }

    return this.coursesRepository.update(id, {
      ...updateCourseDto,
      thumbnailUrl: uploadResult.secure_url,
      thumbnailPublicId: uploadResult.public_id,
    });
  }

  async update(id: string, updateCourseDto: UpdateCourseDto): Promise<Course> {
    return this.coursesRepository.update(id, updateCourseDto);
  }

  async remove(id: string): Promise<void> {
    const existingCourse = await this.findOne(id);
    
    if (existingCourse.thumbnailPublicId) {
      await this.cloudinaryService.deleteFile(existingCourse.thumbnailPublicId).catch(console.error);
    }

    return this.coursesRepository.remove(id);
  }
}

