import { Injectable, NotFoundException } from '@nestjs/common';
import { CoursesRepository } from './courses.repository';
import { CreateCourseDto, UpdateCourseDto } from './dto/course.dto';
import { Course } from './entities/course.entity';

@Injectable()
export class CoursesService {
  constructor(private readonly coursesRepository: CoursesRepository) {}

  async create(createCourseDto: CreateCourseDto): Promise<Course> {
    const course: Course = {
      id: '', // Will be generated by Firestore
      ...createCourseDto,
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    return this.coursesRepository.create(course);
  }

  async findAll(): Promise<Course[]> {
    return this.coursesRepository.findAll();
  }

  async findOne(id: string): Promise<Course> {
    const course = await this.coursesRepository.findById(id);
    if (!course) {
      throw new NotFoundException(`Course with ID ${id} not found`);
    }
    return course;
  }

  async update(id: string, updateCourseDto: UpdateCourseDto): Promise<Course> {
    return this.coursesRepository.update(id, updateCourseDto);
  }

  async remove(id: string): Promise<void> {
    // Check if exists first
    await this.findOne(id);
    return this.coursesRepository.remove(id);
  }
}
